name: "Publish to GodotAssetLib"
on: 
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish to AssetLib
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Godot Asset Lib
        uses: deep-entertainment/godot-asset-lib-action@v0.4.0
        with:
          username: ThePat02
          password: ${{ secrets.PASSWORD_ASSET_LIB }}
          assetId: 1399
